// <auto-generated />
using System;
using Levi9.POS.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi9.POS.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230508121534_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Levi9.POS.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1.maja, Derventa",
                            Email = "marko@gmail.com",
                            GlobalId = new Guid("2c4661b9-897c-4053-80f8-dda5f382857c"),
                            LastUpdate = "133280217345321113",
                            Name = "Marko",
                            Password = "password",
                            Phone = "+387 65 132 527",
                            Salt = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Koste Racina 24, Novi Sad",
                            Email = "aleksa@gmail.com",
                            GlobalId = new Guid("7443ac60-8b5d-4786-9675-42b6f3c1ff7e"),
                            LastUpdate = "133280217345321135",
                            Name = "Aleksa",
                            Password = "password123",
                            Phone = "+387 64 862 476",
                            Salt = "Salt123"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Strumicka 13, Novi Sad",
                            Email = "milos@gmail.com",
                            GlobalId = new Guid("86e36676-8c8c-43ed-acf6-582c205d5ba2"),
                            LastUpdate = "133280217345321150",
                            Name = "Milos",
                            Password = "password123",
                            Phone = "+387 65 912 127",
                            Salt = "Salt123"
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreationDay")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("DocumetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreationDay = "133280217345321182",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("f40d84b7-f90b-446a-b3dc-3caf22816436"),
                            LastUpdate = "133280217345321193"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreationDay = "133280217345321205",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("943546af-6640-4256-9c99-e26f89fcb885"),
                            LastUpdate = "133280217345321217"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CreationDay = "133280217345321231",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("cb2d859d-59a6-44d8-93d7-059d4649cb77"),
                            LastUpdate = "133280217345321242"
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 30,
                            GlobalId = new Guid("d9da34a0-a6ec-4428-8674-c0fca1b43fc1"),
                            LastUpdate = "133280217345320737",
                            Name = "Levi 9 T-Shirt",
                            Price = 10f,
                            ProductImageUrl = "baseURL//nekiurl1.png"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 10,
                            GlobalId = new Guid("b3f20159-45e9-4a3c-b5e5-725a99e63e6e"),
                            LastUpdate = "133280217345320844",
                            Name = "Novis T-Shirt",
                            Price = 15f,
                            ProductImageUrl = "baseURL//nekiurl2.png"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 20,
                            GlobalId = new Guid("ca6962b5-7cd3-4709-8328-8878301e0155"),
                            LastUpdate = "133280217345320876",
                            Name = "Vega IT T-Shirt",
                            Price = 20f,
                            ProductImageUrl = "baseURL//nekiurl3.png"
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.ProductDocument", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ProductDocuments");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DocumentId = 1,
                            Currency = "RSD",
                            Price = 1200f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 2,
                            DocumentId = 2,
                            Currency = "EUR",
                            Price = 10f,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 3,
                            DocumentId = 3,
                            Currency = "USD",
                            Price = 15f,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.HasOne("Levi9.POS.Domain.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.ProductDocument", b =>
                {
                    b.HasOne("Levi9.POS.Domain.Models.Document", "Document")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.POS.Domain.Models.Product", "Product")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Client", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.Navigation("ProductDocuments");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
