// <auto-generated />
using System;
using Levi9.POS.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi9.POS.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
    [Migration("20230510130506_InitialMigration")]
    partial class InitialMigration
========
    [Migration("20230510102847_initial")]
    partial class initial
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Levi9.POS.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1.maja, Derventa",
                            Email = "marko@gmail.com",
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("489322bc-460b-4ffa-952d-b5ab81a41afd"),
                            LastUpdate = "133281975060342291",
========
                            GlobalId = new Guid("5d03ccb9-7a09-49d0-bab3-8ff56aa11c22"),
                            LastUpdate = "133281881272337945",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Marko",
                            PasswordHash = "password",
                            Phone = "+387 65 132 527",
                            Salt = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Koste Racina 24, Novi Sad",
                            Email = "aleksa@gmail.com",
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("ac497f15-59ef-4cf9-81ad-35b8880abbd6"),
                            LastUpdate = "133281975060342306",
========
                            GlobalId = new Guid("abc07698-dfb1-4075-94a5-00f73d512c52"),
                            LastUpdate = "133281881272337986",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Aleksa",
                            PasswordHash = "password123",
                            Phone = "+387 64 862 476",
                            Salt = "Salt123"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Strumicka 13, Novi Sad",
                            Email = "milos@gmail.com",
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("ef0cef6e-7adc-4a9e-bf8e-203a8f7db718"),
                            LastUpdate = "133281975060342314",
========
                            GlobalId = new Guid("d1288461-7eea-43c3-bc2e-0e5eef6baa86"),
                            LastUpdate = "133281881272338028",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Milos",
                            PasswordHash = "password123",
                            Phone = "+387 65 912 127",
                            Salt = "Salt123"
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreationDay")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            CreationDay = "133281975060342338",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("976d48fd-e7ba-45f6-b578-02f612e810f5"),
                            LastUpdate = "133281975060342345"
========
                            CreationDay = "133281881272338083",
                            DocumentType = "INVOICE",
                            GlobalId = new Guid("d1a87fab-26f7-46d3-8201-ab713703ac11"),
                            LastUpdate = "133281881272338098"
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            CreationDay = "133281975060342354",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("721dd915-9975-410a-bfdd-51ca9d20280f"),
                            LastUpdate = "133281975060342359"
========
                            CreationDay = "133281881272338113",
                            DocumentType = "INVOICE",
                            GlobalId = new Guid("d572a803-ab28-49a0-b1f9-d163f2ad22ff"),
                            LastUpdate = "133281881272338126"
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            CreationDay = "133281975060342366",
                            DocumetType = "INVOICE",
                            GlobalId = new Guid("ff0c1315-4a19-4f1c-829f-27027902884a"),
                            LastUpdate = "133281975060342372"
========
                            CreationDay = "133281881272338141",
                            DocumentType = "INVOICE",
                            GlobalId = new Guid("e10be4e8-e414-43c8-82a2-514c740703ee"),
                            LastUpdate = "133281881272338153"
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 30,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("5533268a-fbad-4817-ac83-cdb057d9fc01"),
                            LastUpdate = "133281975060342021",
========
                            GlobalId = new Guid("ef7d3675-151e-47ae-9923-3ea709693475"),
                            LastUpdate = "133281881272337420",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Levi 9 T-Shirt",
                            Price = 10f,
                            ProductImageUrl = "baseURL//nekiurl1.png"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 10,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("58e72cde-0802-447b-bf19-008017f4af69"),
                            LastUpdate = "133281975060342108",
========
                            GlobalId = new Guid("45edb050-4476-4f2e-86fa-1015e969fcc7"),
                            LastUpdate = "133281881272337531",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Novis T-Shirt",
                            Price = 15f,
                            ProductImageUrl = "baseURL//nekiurl2.png"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 20,
<<<<<<<< HEAD:Levi9.POS.Domain/Migrations/20230510130506_InitialMigration.Designer.cs
                            GlobalId = new Guid("4535b569-e936-4120-9054-c6b301f9495e"),
                            LastUpdate = "133281975060342130",
========
                            GlobalId = new Guid("d12e1f4f-2ae9-4edd-8d75-60f08b3caeb0"),
                            LastUpdate = "133281881272337552",
>>>>>>>> 75b6e89089cc7e3bdcdff7d1c7b441cbe7c47637:Levi9.POS.Domain/Migrations/20230510102847_initial.Designer.cs
                            Name = "Vega IT T-Shirt",
                            Price = 20f,
                            ProductImageUrl = "baseURL//nekiurl3.png"
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.ProductDocument", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ProductDocuments");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DocumentId = 1,
                            Currency = "RSD",
                            Price = 1200f,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 2,
                            DocumentId = 2,
                            Currency = "EUR",
                            Price = 10f,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 3,
                            DocumentId = 3,
                            Currency = "USD",
                            Price = 15f,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.HasOne("Levi9.POS.Domain.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.ProductDocument", b =>
                {
                    b.HasOne("Levi9.POS.Domain.Models.Document", "Document")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.POS.Domain.Models.Product", "Product")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Client", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Document", b =>
                {
                    b.Navigation("ProductDocuments");
                });

            modelBuilder.Entity("Levi9.POS.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
